env:
  ELIXIR_ASSERT_TIMEOUT: 2000
  ELIXIRC_OPTS: "--warnings-as-errors"
  ERLC_OPTS: "+warnings_as_errors"
  LANG: C.UTF-8

test_template: &DEFAULT_TEST_SETTINGS
  # don't cancel the task execution if it's master or a release branch
  auto_cancellation: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH !=~ 'v\d+\.\d+.*'

test_linux_task:
  <<: *DEFAULT_TEST_SETTINGS

  container:
    image: buildpack-deps:trusty
    cpu: 8
    memory: 1536Mi

  env:
    PATH: "${CIRRUS_WORKING_DIR}/otp/bin:${PATH}"

  name: Linux, ${OTP_RELEASE}, Ubuntu 14.04
  env:
    matrix:
      CIRRUS_CLONE_DEPTH: 50
      CIRRUS_CLONE_DEPTH: 1
      CIRRUS_CLONE_DEPTH: 0
